ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb, "1000"]
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.11
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [--fix, --show-fixes]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        args: [--ignore-words-list, "ans,thirties"]

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.8.3
    hooks:
      - id: prettier
        types_or: [yaml, markdown, json]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.1
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format

  - repo: local
    hooks:
      - id: format-justfile
        name: Format justfile
        entry: just --fmt --unstable
        language: system
        files: '(^|/)justfile$|\.just$'
        pass_filenames: false
